apiVersion: v1
kind: ServiceAccount
metadata:
  name: execution-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: execution-role
  namespace: default
rules:
  # Service, ConfigMap, Pod, Deployment
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "configmaps", "deployments"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: execution-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: execution-sa
    namespace: default
roleRef:
  kind: Role
  name: execution-role
  apiGroup: rbac.authorization.k8s.io