name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy App
        run: |
          echo "ðŸ“Œ Entering project directory"
          cd /home/ubuntu/serverless/app/execution/execution

          echo "â¬‡ï¸ Pulling latest code"
          git pull origin master

          echo "âš™ï¸ Building Go App"
          go build -o server .

          echo "ðŸ”ª Killing old server if any"
          pkill server || true

          echo "ðŸš€ Starting new server"
          nohup ./server > server.log 2>&1 &

          echo "ðŸ“œ Showing running process"
          pgrep -l server

          echo "ðŸŽ‰ Done! Deployment Successful"

