name: Deploy to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l2r2n3p5

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: public.ecr.aws/l2r2n3p5
          ECR_REPOSITORY: serverless-bistro-dispatcher
          IMAGE_TAG: latest
        run: |
          # 이미지를 ECR 주소 이름으로 빌드
          docker build -t gateway -f /home/ubuntu/serverless/app/execution/execution/Dockerfile .

          docker tag gateway:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # 생성된 이미지를 AWS ECR로 업로드
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f /home/ubuntu/serverless/app/execution/execution/k8s/rbac.yaml
          kubectl apply -f /home/ubuntu/serverless/app/execution/execution/k8s/redis.yaml
          kubectl apply -f /home/ubuntu/serverless/app/execution/execution/k8s/gateway.yaml

      - name: Restart deployments (to use new image)
        run: |
          kubectl rollout restart deployment --all || true

      - name: Check status
        run: |
          kubectl get pods
          kubectl get services
